/*
 * Copyright Luke Wallin 2012
 */
package fractal;

import java.awt.Dimension;
import java.awt.Graphics;

/**
 *
 * @author Luke
 */
public class AutoFractalWindow extends javax.swing.JFrame {

    private Fractal fractal;
    
    /**
     * Creates new form FractalWindow
     */
    public AutoFractalWindow(Fractal _fractal) {
        fractal=_fractal;
        initComponents();
        
//        while(getBufferStrategy() == null){
//            createBufferStrategy(2);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mouseWheel(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AutoFractalWindow.this.mouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AutoFractalWindow.this.mousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AutoFractalWindow.this.mouseDragged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseWheel(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mouseWheel
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseWheel

    private void mouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseDragged

    private void mousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mousePressed

    private void mouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseReleased

     public void paint(Graphics g){
        //Graphics _g = getBufferStrategy().getDrawGraphics();
        
        Dimension d = getSize();
        
        //fractal.draw(g,d.width,d.height);
//        getBufferStrategy().show();
//        _g.dispose();
        
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
